### ISSUE TITLE
Uncaught in promise error

### ISSUE THREAD

**Issue by JeDebute01** [BesTKiLLeR4050/fivem-paintball#1]
Everythink is in the screen -> 
![Capture d’écran 2021-06-17 074145](https://user-images.githubusercontent.com/18090946/122338142-9420d100-cf3f-11eb-87da-3a551e9c3903.png)

I have this message when i join a game and after i close the menu

**Comment by BesTKiLLeR4050** [comment]
Hi, locate this file: **html/assets/js/script.js**, open the file and edit the resource name in second line to: **fivem-paintball**

**Comment by JeDebute01** [comment]
I test it later ;) Thank's for this ^^ And i have a question. It's instanced? (Like with plugin "instance" or everyone can see and hear battle? On a server RP it's hard to fight in town or in supermarket xD (I think i put the battleground long LONGGGG distance of town xD

**Comment by BesTKiLLeR4050** [comment]
Yeah, it's instanced but not with the instance script, every lobby has a different world

**Comment by JeDebute01** [comment]
Wahou ! Insane ! I love you ;) My future players will love this! Thank's for your share and very good job with the UI etc.

**Comment by BesTKiLLeR4050** [comment]
Your welcome! ❤️
